#ifndef INCLUDE_LINEAL_LINEAR_SOLVER_CONJUGATE_GRADIENTS_HPP
#define INCLUDE_LINEAL_LINEAR_SOLVER_CONJUGATE_GRADIENTS_HPP

// IWYU pragma: begin_exports
#include "conjugate-gradients/solver.hpp"
// IWYU pragma: end_exports

#endif // INCLUDE_LINEAL_LINEAR_SOLVER_CONJUGATE_GRADIENTS_HPP
