#ifndef INCLUDE_LINEAL_LINEAR_SOLVER_ITERATIVE_STATIONARY_GAUSS_SEIDEL_VARIANT_HPP
#define INCLUDE_LINEAL_LINEAR_SOLVER_ITERATIVE_STATIONARY_GAUSS_SEIDEL_VARIANT_HPP

// IWYU pragma: begin_exports
#include "gauss-seidel-variant/solver.hpp"
#include "gauss-seidel-variant/sweep.hpp"
// IWYU pragma: end_exports

#endif // INCLUDE_LINEAL_LINEAR_SOLVER_ITERATIVE_STATIONARY_GAUSS_SEIDEL_VARIANT_HPP
