#ifndef INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_TRANSPORT_INFO_HPP
#define INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_TRANSPORT_INFO_HPP

// IWYU pragma: begin_exports
#include "info/simple.hpp"
// IWYU pragma: end_exports

#endif // INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_TRANSPORT_INFO_HPP
