#ifndef INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_AGGREGATE_MAP_HPP
#define INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_AGGREGATE_MAP_HPP

// IWYU pragma: begin_exports
#include "aggregate-map/multithread.hpp"
// IWYU pragma: end_exports

#endif // INCLUDE_LINEAL_LINEAR_SOLVER_MULTIGRID_AGGREGATE_MAP_HPP
